import { Navbar } from "@/components/Navbar";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Lora } from "next/font/google";
import AnimatedRoutes from "@/components/AnimatedRoutes";

// const inter = Inter({ subsets: ["latin"] });
const lora = Lora({
  subsets: ["latin"],
});
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <body className={lora.className}> */}
        <Navbar />
        <div className="md:container md:mx-auto">{children}</div>
      </body>
    </html>
  );
}
